export const AppState = {
  IDLE: "IDLE",
  GENERATING_QUESTIONS: "GENERATING_QUESTIONS",
  INTERVIEW_IN_PROGRESS: "INTERVIEW_IN_PROGRESS",
  ANALYZING_RESULTS: "ANALYZING_RESULTS",
  SHOW_SUMMARY: "SHOW_SUMMARY",
};